#!/bin/bash
launcher="./Documents/Distributed/Project/launcher.sh"
username="pdavou"
old_ifs=$IFS
IFS=$'\n'
if [ $# -eq 2 ]; then
	
	export rmihosts=""
	for i in $(cat $1); do
		echo "Connecting to " $username"@"$(echo $i | awk '{print $1}')
		echo "Running screen $launcher $(echo $i | awk '{print $2 " "$3}')"
		ssh -t  $username"@"$(echo $i | awk '{print $1}')  screen $launcher $(echo $i | awk '{print $2 " " $3}')
		export rmihosts="$rmihosts $(echo $i | awk '{print $1}')"
	done
	echo "Hosts launched on $rmihosts"
	ssh -t  $username"@"$2 screen $launcher 4031 $rmihosts
else
	echo "usage: alllauncher config_file middleware_host"
	exit 1
fi
