#!/bin/bash
dir="./Documents/Distributed/Project"
launcher="./launcher.sh"
username="pdavou"
old_ifs=$IFS
IFS=$'\n'
if [ $# -eq 2 ]; then
	
	export rmihosts=""
	for i in $(cat $1); do
		host=$(echo $i | awk '{print $1}')
		args=$(echo $i | awk '{print $2 " " $3}')
		command="cd $dir" '&&' "screen $launcher $args"
		echo "Connecting to " $username"@"$host
		echo "Running screen $launcher $args"
		ssh -t $username"@"$host  cd $dir '&&' screen $launcher $args
		export rmihosts="$rmihosts $host"
	done
	echo "Hosts launched on $rmihosts"
	ssh -t  $username"@"$2 cd $dir '&&' screen $launcher 4031 $rmihosts
else
	echo "usage: alllauncher config_file middleware_host"
	exit 1
fi
